hr:
  api:
    permit-all:
      register:
        description: 'Sisteme kullanıcı tanımlamak için kullanılır.'
      authenticate:
        description: 'Sisteme giriş yapıp token almak için kullanılır.'
      refresh-token:
        description: 'Mevcut token bittiğinde yenilemek için kullanılır.'
      get-authorizations-by-role-id:
        description: 'Role id sine göre kişinin yetkisinin olduğu aksiyonları getirir.'
      get-menulist-by-rolecode:
        description: 'Role koduna göre erişebileceği menülerin getirilmesi'
      get-current-user:
        description: 'Username değerine göre kullanıcının bilgilerini getiren ve Authorization olup olmadığını sağlanılan servistir.'