hr:
  api:
    permit-all:
      register:
        description: 'Sisteme kullanıcı tanımlamak için kullanılır.'
      authenticate:
        description: 'Sisteme giriş yapıp token almak için kullanılır.'
      refresh-token:
        description: 'Mevcut token bittiğinde yenilemek için kullanılır.'